dsymm_ob:
  data: "data/dsymm_ob/jobs/dsymm_ob.csv"
  procs:
    - 4
    - 12
    - 20
    - 36
    - 48
  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    #- viz.barchart.create_rsm_error_barchart
    - viz.barchart.create_rsm_percent_barchart
    - viz.heatmap.create_heatmap
    - viz.sunburst.sunburst
    - viz.linechart.raw_values_per_proc_config
    # - viz.barchart.load_imbalance
  rsm_use_nn_solver: True
  name: "dsymm_ob"

main:
  tasks:
    - dsymm_ob
    - viz.dashboard.dashboard_init

  arch: wave_cpu
  data_rescale: True
  rsm_iters: 100
  rsm_print: True
  rsm_use_nn_solver: False
  port: 7500
