dgemm_naive:
  data: "data/dgemm_naive/jobs/dgemm_naive.csv"
  procs:
    - 1
    - 4
    - 12
    - 20
    - 36
    - 48
  rsm_use_nn_solver: True
  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    #- viz.barchart.create_rsm_error_barchart
    - viz.barchart.create_rsm_percent_barchart
    - viz.heatmap.create_heatmap
    - viz.sunburst.sunburst
    - viz.linechart.raw_values_per_proc_config
    # - viz.barchart.load_imbalance
  name: "dgemm_naive"

main:
  tasks:
    - dgemm_naive
    - viz.dashboard.dashboard_init

  arch: wave_cpu
  data_rescale: True
  rsm_iters: 1000
  rsm_print: True
  rsm_use_nn_solver: False
  port: 7500
